name: VHDL library CI
on:
  push:
  pull_request:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Run VUnit tests
      uses: ./
      with:
        cmd: run.py