name: VHDL library CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - uses: docker://ghdl/vunit:mcode
      with:
        args: run.py